//
// Created by 염희돈 on 2019-09-27.
//

#ifndef ALGORITHM_DATASTRUCTURE_INSERTIONSORT_H
#define ALGORITHM_DATASTRUCTURE_INSERTIONSORT_H

void insertionSort(int *array, int length);



#endif //ALGORITHM_DATASTRUCTURE_INSERTIONSORT_H
